const ACTION_TYPES = {
    API_LOADING: 'API_LOADING',
    API_SUCCESS: 'API_SUCCESS',
    API_ERROR: 'API_ERROR',
    MOVIE_SUCCESS: 'MOVIE_SUCCESS',
    MOVIE_ERROR: 'MOVIE_ERROR',
    MOVIE_LOADING: 'MOVIE_LOADING'
};

export default ACTION_TYPES;